name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.TOKEN_FOR_DOCKER }}" | docker login ghcr.io -u lai-yt --password-stdin
      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.prod -t ghcr.io/docentre/docentre-backend .
          docker push ghcr.io/docentre/docentre-backend

  k8s:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load kubeconfig
        run: |-
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode >> ~/.kube/config

      - name: Load k8s files
        run: |-
          mkdir k8s
          echo "${{ secrets.KUBE_BACKEND_FILE }}" | base64 --decode >> k8s/deploy-backend.yaml

      - name: Stop old k8s
        working-directory: ./k8s
        run: |-
          kubectl delete -f deploy-backend.yaml

      - name: Apply new k8s
        if: always()
        working-directory: ./k8s
        run: |-
          kubectl apply -f deploy-backend.yaml
