name: Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.TOKEN_FOR_DOCKER }}" | docker login ghcr.io -u lai-yt --password-stdin
      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.prod -t ghcr.io/docentre/docentre-backend .
          docker push ghcr.io/docentre/docentre-backend
